### ISSUE TITLE
pedantic dep prevent null safety migration

### ISSUE THREAD

**Issue by Miamoto-Musashi** [juliansteenbakker/another_transformer_page_view#2]
pls upgrade to lints since pedantic is deprcated

`dart pub upgrade --major-versions`

`  pedantic 1.11.1 (discontinued replaced by lints)`

`dart pub deps`

```bash
|-- another_transformer_page_view 1.0.1
|   |-- pedantic 1.11.1
```

thanks

**Comment by juliansteenbakker** [comment]
Fixed, thanks !
